version: "3"
volumes:
  nextcloud:
  database:
  npm:
networks:
  bahut-net:

services:
  bnextcloud:
    image: nextcloud
    container_name: bnextcloud
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - nextcloud:/var/www/html
      - /media/paiol:/var/www/html/data
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=${TRUSTED_DOMAINS}
      - OVERWRITEPROTOCOL=https
    networks:
      - bahut-net
  bdatabase:
    image: mariadb
    container_name: bdatabase
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - database:/var/lib/mysql/data
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_HOST=${DB_HOST}
    networks:
      - bahut-net
  bnpm:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: bnpm
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - npm:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - bahut-net
