version: "3"
volumes:
  bahut-nextcloud:
  bahut-database:
networks:
  bahut-net:

services:
  bnextcloud:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: bnextcloud
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
      - /media/paiol:/var/www/html/data
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=${TRUSTED_DOMAINS}
      - OVERWRITEPROTOCOL="https" 
    networks:
      - bahut-net
  bdatabase:
    image: mariadb
    container_name: bdatabase
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - bahut-db:/var/lib/mysql/data
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - bahut-net
  bnpm:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: bnpm
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./data:/data
    networks:
      - bahut-net
