version: "3"
volumes:
  bahut-nextcloud:
  bahut-database:
networks:
  bahut-net:

services:
  bnextcloud:
    image: nextcloud
    container_name: bnextcloud
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
      - /media/paiol:/data
    networks:
      - bahut-net
  bdatabase:
    image: mariadb
    container_name: bdatabase
    restart: unless-stopped
    volumes:
      - bahut-db:/var/lib/mysql/data
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
    networks:
      - bahut-net
  bnpm:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: bnpm
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./data:/data
    networks:
      - bahut-net

