version: "3"
volumes:
  /media/paiol:
  bahut-nextcloud:
  bahut-database:
networks:
  bahut-net:

services:
  bnextcloud:
    image: nextcloud
    restart: always
    volumes:
      - /media/paiol:/data
      - bahut-nextcloud:/var/www/html
    networks:
      - bahut-net
  bdatabase:
    image: postgres
    restart: always
    volumes:
      - bahut-database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - bahut-net

